# Generated by Django 2.2.3 on 2019-07-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, null=True)),
                ('surname', models.CharField(default='', max_length=150, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(default='', max_length=100, null=True)),
                ('city', models.CharField(default='', max_length=150, null=True)),
                ('bachelor', models.BooleanField()),
                ('masters', models.BooleanField()),
                ('doctor_degree', models.BooleanField()),
            ],
        ),
    ]
