# Generated by Django 2.2.3 on 2019-07-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0004_auto_20190716_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.FileField(default='', null=True, upload_to='profile_pictures'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
