# Generated by Django 2.2.3 on 2019-07-16 18:59

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0006_person_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bachelor',
        ),
        migrations.RemoveField(
            model_name='person',
            name='doctor_degree',
        ),
        migrations.RemoveField(
            model_name='person',
            name='masters',
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='', help_text='Contact phone number', max_length=31),
        ),
    ]
