# Generated by Django 2.2.3 on 2019-07-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0007_auto_20190716_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='short_description',
            field=models.TextField(default='', null=True),
        ),
    ]
