# Generated by Django 2.2.3 on 2019-07-17 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0009_personexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personexperience',
            old_name='user_id',
            new_name='user',
        ),
    ]
