# Generated by Django 2.2.3 on 2019-07-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0011_personlinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlinks',
            name='facebook',
            field=models.URLField(default='', null=True),
        ),
    ]
