# Generated by Django 2.2.3 on 2019-07-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0012_personlinks_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlinks',
            name='linkedin',
            field=models.URLField(default='', null=True),
        ),
        migrations.CreateModel(
            name='PersonTechnologyStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloud', models.TextField(default='', null=True)),
                ('programming', models.TextField(default='', null=True)),
                ('os', models.TextField(default='', null=True)),
                ('web_development', models.TextField(default='', null=True)),
                ('databases', models.TextField(default='', null=True)),
                ('machine_learning', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_me.Person')),
            ],
        ),
    ]
