# Generated by Django 2.2.3 on 2019-07-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0013_auto_20190718_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlinks',
            name='facebook',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='personlinks',
            name='github',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='personlinks',
            name='instagram',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='personlinks',
            name='kaggle',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='personlinks',
            name='linkedin',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
