# Generated by Django 2.2.3 on 2019-08-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_me', '0015_personbooks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personlinks',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personlinks',
            name='github',
        ),
        migrations.RemoveField(
            model_name='personlinks',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='personlinks',
            name='kaggle',
        ),
        migrations.RemoveField(
            model_name='personlinks',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='personlinks',
            name='link_to_social',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='personlinks',
            name='social_img',
            field=models.FileField(default='', null=True, upload_to='social_covers'),
        ),
    ]
